export const COACHING_REPOSITORY = {
    exposures: [
        "Every exposure is a seed planted. Keep sowing!",
        "Prospect is your best friend. Share a resource and let it do the heavy lifting.",
        "A quiet mouth is a closed business. Great job opening yours!",
        "You are enabling someone to affordably live a just and secure life today.",
        "Disrupt the justice system one exposure at a time.",
        "The more people you show, the faster you grow. Keep going!",
        "Just press play! Get the info in front of them.",
        "Don't judge the prospect; just give them the information.",
        "An exposure today is a membership tomorrow. Great work!",
        "You're not selling, you're sharing. Keep sharing the LegalShield mission.",
        "Who's next? Your next diamond is just one exposure away.",
        "Activity breeds results. Every single exposure counts towards your goals.",
        "Are you dropping LSEngage links? Keep your pipeline full!",
        "We are disruptors of the justice system. Make sure everyone knows it.",
        "Your duty is to inform. Their duty is to decide. Keep informing!",
        "Every contact brings you closer to your Vested Goal.",
        "Don't stop now. Momentum is built on consistent exposures.",
        "Legal access for all starts with you starting a conversation.",
        "Privacy protection is a necessity. Make sure they know about IDShield.",
        "Who else needs to hear this? Keep the exposures coming.",
        "The Golden Rule: share with others what you'd want shared with you.",
        "Plant the seed, water it, and watch it grow. Great exposure!",
        "You never know who is praying for our opportunity today.",
        "Expose, expose, expose! That's the name of the game.",
        "Every click on an LSEngage link is a step closer to Performance Club."
    ],
    followUps: [
        "The fortune is in the follow-up!",
        "Remember the '5 to 12' Rule: 80% of memberships are sold between the 5th and 12th contact.",
        "Don't give up! Most people say no until they say yes. Follow up again.",
        "A follow-up is just showing you care. Keep caring!",
        "Following up is Extreme Ownership of your business.",
        "Did you know? It takes 5 to 12 exposures for most to decide. Stay in the game!",
        "They aren't ignoring you; they are just busy. Reach back out!",
        "Professionals follow up. Amateurs give up. Way to be a pro!",
        "Keep moving them from exposure to exposure until a decision is made.",
        "Every follow-up builds trust. Trust builds businesses.",
        "Check in with a smile. Sometimes timing is everything.",
        "The '5 to 12' Rule is your best friend. Be persistent and patient.",
        "Are they at contact point 4? Don't stop now, you're almost there!",
        "Follow up with providing value. Give them another reason to look.",
        "Persistence is a sign of belief. Show them you believe in LegalShield.",
        "We are disruptors. Disruption requires consistent follow-up.",
        "Keep the conversation alive. The fortune is truly in the follow up.",
        "A polite follow-up shows professionalism and dedication.",
        "It's not highly persistent, it's highly committed. Great job!",
        "You are one follow-up closer to unlocking residual income.",
        "Don't let the seeds you planted die of thirst. Water them with a follow-up!",
        "Following up is just asking for a decision. You deserve an answer.",
        "Keep track, stay organized, and follow through.",
        "The '5 to 12' Rule is a statistical fact. Play the numbers!",
        "Your follow-up might just be the solution to their biggest problem."
    ],
    presentations: [
        "You're showing the plan! This is where the magic happens.",
        "A full presentation means full understanding. Outstanding work!",
        "When they see the whole picture, the vision becomes clear.",
        "Show them how we disrupt the justice system!",
        "Presenting is leading. Way to step up and lead.",
        "The more presentations you do, the luckier you get.",
        "Are they seeing the LegalShield and IDShield value? Great job presenting.",
        "You're painting a picture of a more secure life. Keep presenting.",
        "Every presentation is practice. Every practice makes you better.",
        "Whether it's a PBR or a Zoom, showing the plan is the key.",
        "Help them see the Vested Goal: residual income for a lifetime.",
        "If you show the plan, the plan will show you the money.",
        "Great job taking Extreme Ownership of your prospect list.",
        "A presentation opens the door to joining forces.",
        "Keep it simple, keep it exciting, and show the plan!",
        "They can't join if they don't see it. Way to get them on a presentation.",
        "Disrupt the justice system by showing everyone our mission.",
        "Every presentation brings you closer to Elite production.",
        "Performance Club is built on consistent presentations.",
        "Master the presentation and you master your future.",
        "You are the messenger of justice and secure lives.",
        "Let the tools do the talking during the presentation. Awesome job.",
        "A presentation a day keeps the slump away!",
        "You just shared the best kept secret in North America.",
        "They see the value because you showed them the value."
    ],
    threeWayCalls: [
        "Joining Forces via a 3-way call is the smartest way to build.",
        "Edification is the secret sauce. Great job using your expert!",
        "You don't have to know it all. Use 3-way calls to close!",
        "Third-party validation is a game changer.",
        "A 3-way call proves that they will have a team supporting them, too.",
        "Joining Forces! Way to leverage your leadership.",
        "The triangle of edification works every time.",
        "Let your expert take the pressure off you. Fantastic!",
        "A 3-way call is the bridge between a prospect and a new associate.",
        "Leverage your upline. That's what they are there for!",
        "Teamwork makes the dream work. Joining Forces in action!",
        "Edify, introduce, and mute. Let the expert close.",
        "You are letting the system work for you.",
        "Every 3-way call builds your belief and their confidence.",
        "The Golden Rule: support others as your team supports you.",
        "Using 3-way calls shows the prospect our culture of support.",
        "It's not about what you know, it's about who you know. Use your expert!",
        "Validation brings hesitation to an end.",
        "Great job getting out of the way and letting the expert speak.",
        "A 3-way call brings clarity and urgency.",
        "Joining Forces builds massive momentum.",
        "You are mastering the art of the 3-way call. Keep it up!",
        "An expert on the line means a membership in the pipeline.",
        "This is how we build extreme ownership as a team.",
        "3-way calls speed up the '5 to 12' rule exponentially."
    ],
    teamSupport: [
        "Joining Forces! Supporting your team is true leadership.",
        "Extreme Ownership means caring about your team's success as much as your own.",
        "A rising tide lifts all boats. Way to lift your team!",
        "When you help someone else win, you win too.",
        "The Golden Rule in action: treat your team how you want to be treated.",
        "Team support builds a business that lasts a lifetime.",
        "You are building a culture of success. Keep supporting your team!",
        "Leadership is action, not position. Great leadership today.",
        "A quick call to a team member changes their whole day.",
        "Supporting your team secures your Vested Goal.",
        "You are the glue that holds your team together.",
        "Help them hit Performance Club, and you'll hit it too.",
        "We are disruptors, and we disrupt together as a team.",
        "Encouragement is the fuel of our business. Way to fuel your team!",
        "Your team appreciates your Extreme Ownership.",
        "A simple text or call can turn a team member's week around.",
        "Leadership is about making others better. You are doing it!",
        "Together Everyone Achieves More. Joining Forces!",
        "You are building a strong foundation for residual income.",
        "A supported team is an unstoppable team.",
        "Mentoring your team is the highest form of duplication.",
        "Great job pouring belief into your associates.",
        "Your team reflects your effort. Keep leading by example.",
        "Joining Forces means we never build alone.",
        "You're not just building a team, you're building a family."
    ],
    membershipsSold: [
        "BOOM! Another membership sold. You are disrupting the justice system!",
        "Yes! Every membership brings you closer to your Vested Goal.",
        "You're securing a lifetime of residual income. Incredible job!",
        "Performance Club is calling your name! Keep selling those memberships.",
        "You just provided someone with affordable legal access and peace of mind.",
        "IDShield and LegalShield – protecting families one policy at a time.",
        "That’s income for today and residual for tomorrow!",
        "Every sale is a family protected. You're doing noble work.",
        "You are on fire! Let the momentum carry you to the next sale.",
        "Vested! Maintain that $100 personal premium for long-term freedom.",
        "A membership sold is the '5 to 12' rule paying off. Persistence wins!",
        "Awesome! You are officially a disruptor of the justice system.",
        "Performance Club requires consistency, and you are nailing it.",
        "Celebrate the win, then go find the next one!",
        "You just expanded the LegalShield footprint. Massive impact!",
        "A signed application is the result of Extreme Ownership of your goals.",
        "Keep your pipeline full and the memberships will keep falling out.",
        "Residual income is sweet, isn't it? Great job!",
        "You're helping everyone affordably live a just and secure life.",
        "Who's next? Don't stop at one, make it a streak!",
        "Joining Forces with Provider Law Firms to protect another family.",
        "That membership secures your business foundation.",
        "Selling memberships is how we change the world. Way to go!",
        "Incredible execution. Enjoy the victory!",
        "You are building an empire of protection and residual income."
    ],
    dailyDisciplines: [
        "Sharpening the saw makes cutting the tree so much easier.",
        "Personal development today is profit tomorrow.",
        "Your business grows only as fast as you grow.",
        "A healthy body fuels a healthy business. Great job exercising!",
        "Extreme Ownership of your mind and body is the key to success.",
        "You can't pour from an empty cup. Good job filling yours up today.",
        "Daily disciplines compound into massive success.",
        "Mindset is everything. Feed your brain the right stuff.",
        "Consistency in the small things leads to victory in the big things.",
        "Listening to audios and reading books is the diet of a champion.",
        "Sweat equity pays off. Keep pushing yourself physically and mentally.",
        "A focused mind and active body make you unstoppable.",
        "You are investing in your greatest asset: yourself.",
        "Disrupt your old habits to make room for new success.",
        "The Vested Goal requires a vested mindset. Keep growing.",
        "Leaders are readers. What are you reading today?",
        "Daily discipline is the bridge between goals and accomplishment.",
        "A strong morning routine sets up a successful day.",
        "Physical exercise releases the energy needed to build your business.",
        "Personal development ensures you are always ready for the next level.",
        "Control your morning, conquer your day.",
        "Mindset is the thermostat for your success. Turn it up!",
        "Great job taking time for self-care and growth.",
        "Your future self will thank you for today's discipline.",
        "Success is rented, and the rent is due every day. Way to pay the rent!"
    ],
    rejections: [
        "SW4! Some Will, Some Won't, So What? Someone's Waiting!",
        "A 'No' today is just a 'Not right now'. Move to the next diamond.",
        "Every 'No' brings you closer to a 'Yes'. Keep going!",
        "Don't take it personally. They are saying no to the timing, not to you.",
        "SW4 Mindset: Someone out there is praying for this opportunity right now. Go find them!",
        "The fastest way to success is to double your rate of failure.",
        "A rejection is just a redirection to your next superstar.",
        "Dust yourself off. The SW4 mindset means we never lose momentum.",
        "Next! Extreme Ownership means you keep going regardless of the response.",
        "It takes thick skin to disrupt the justice system. You have it!",
        "Another 'No' just means you are active. Activity is always good.",
        "We are looking for the looking. If they aren't looking, move on!",
        "SW4! You can't say the wrong thing to the right person.",
        "Your Vested Goal doesn't depend on one person's 'No'. It depends on your hustle.",
        "Smile and dial. The Golden Rule means we politely accept their 'No' and move forward.",
        "A 'No' is just data. Use it to refine your approach and find the next 'Yes'.",
        "Don't let one 'No' derail your day. Someone is waiting for you!",
        "The most successful people in LegalShield have heard 'No' the most.",
        "SW4! Clear the pipeline and make room for the right people.",
        "Every top earner was built on a mountain of rejections. Keep climbing.",
        "They missed out, but someone else won't. Keep sharing!",
        "A 'No' just saves you time. Thank them and move on.",
        "SW4 means emotional detachment from the outcome. Great job staying strong.",
        "You are sifting and sorting, not convincing. On to the next!",
        "Celebrate the 'No' because it proves you are in the game!"
    ]
};
